### ISSUE TITLE
Bash Profile Not Set Correctly

### ISSUE THREAD

**Issue by wstrater** [BretFisher/shpod#41]
When I run `shpod` with `docker run -it --rm bretfisher/shpod bash`, the profile does not appear to be correctly set up and I get the following.

```
bash: kube_ps1: command not found
[0.0.0.0] () root@d68972967c6c ~
$ ls
bash: kube_ps1: command not found
[0.0.0.0] () root@d68972967c6c ~
$ 
```

If I load the `kube_ps1.sh` profile, the error goes away.

```
. /etc/profile.d/kube-ps1.sh
[0.0.0.0] (kubernetes:default) root@d68972967c6c ~
$ ls
[0.0.0.0] (kubernetes:default) root@d68972967c6c ~
$ 
```

If I start `bash` simulating a login, the profiles are run but the results are different.

```
bash --login
d0b35017604b:~# ls
d0b35017604b:~#
```

Wes.

**Comment by BretFisher** [comment]
Thanks, let me check.

**Comment by BretFisher** [comment]
Also, the IP in the prompt is missing on some K8s distros

**Comment by BretFisher** [comment]
Looks like this also affects `.spec.clusterIP` in setting envvars. This video won't work if it returns 0.0.0.0 https://www.udemy.com/course/kubernetesmastery/learn/lecture/17071016#overview



![Image](https://user-images.githubusercontent.com/792287/184635065-9d8ab70b-045b-4c33-91b8-46efffd227db.png)

**Comment by dixon1e** [comment]
Just ran into this, it happens when trying to access the shpod using:
`kubectl exec -it shpod -- /bin/bash -n shpod`

**Comment by BretFisher** [comment]
@wstrater lol years later and it looks like we've fixed this

@dixon1e I believe this is the correct command if the pod is already running and you want a 2nd shell `kubectl exec -it -n shpod shpod -- /bin/bash`

I'm going to close but feel free to comment if you need anything else.

**Comment by dixon1e** [comment]
@BretFisher is a perseverant fellow :)
